version: 24.04.2
spin_groups:
  kubuntu:
    name: Kubuntu
    spins:
      - name: kubuntu
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/kubuntu/releases/24.04.2/release/
            path_template: kubuntu-{{ version }}-desktop-amd64.iso
            sha256: 'e84c3cb8a9e91504fabbc4763adaacfee0ebd27ef988529dadafb9c53276fb4b'
            size: 4527759360
  xubuntu:
    name: Xubuntu
    spins:
      - name: xubuntu
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/xubuntu/releases/24.04.2/release/
            path_template: xubuntu-{{ version }}-desktop-amd64.iso
            sha256: 'ba76abf526b4c7ab22e8125cca69547f76559f703bd357c54bdf5d74be0bfd2b'
            size: 4242739200
  lubuntu:
    name: Lubuntu
    spins:
      - name: lubuntu
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/lubuntu/releases/24.04.2/release/
            path_template: lubuntu-{{ version }}-desktop-amd64.iso
            sha256: 'd29e07f791eec68f76521bd8fecd2fb15507c9aab9f8197979cbc70e117dacb1'
            size: 3352426496
  ubuntu-mate:
    name: Ubuntu MATE
    spins:
      - name: ubuntu-mate
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/ubuntu-mate/releases/24.04.2/release/
            path_template: ubuntu-mate-{{ version }}-desktop-amd64.iso
            sha256: 'ec1399cf90678c29ee1f80055826b21a3d90f59d50d154e5ea70b1931ce909c9'
            size: 4301398016
  ubuntu-budgie:
    name: Ubuntu Budgie
    spins:
      - name: ubuntu-budgie
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/ubuntu-budgie/releases/24.04.2/release/
            path_template: ubuntu-budgie-{{ version }}-desktop-amd64.iso
            sha256: '0b9fd288f7ad2d3936187c7f9ebf74aa755068fa5c5dc33520f40b9ba88403a1'
            size: 4248414208
  ubuntu-studio:
    name: Ubuntu Studio
    spins:
      - name: ubuntu-studio
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/ubuntustudio/releases/24.04.2/release/
            path_template: ubuntustudio-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  edubuntu:
    name: Edubuntu
    spins:
      - name: edubuntu
        release: 24.04.2
        version: 24.04.2
        release_title: 24.04.2
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/edubuntu/releases/24.04.2/release/
            path_template: edubuntu-{{ version }}-desktop-amd64.iso
            sha256: '068359bc3bf803be0d1aea61f29384e7446451b3410f1e3dd1317ec1ff55c59f'
            size: 6296694784
