version: 24.04.1
spin_groups:
  kubuntu:
    name: Kubuntu
    spins:
      - name: kubuntu
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/kubuntu/releases/24.04.1/release/
            path_template: kubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  xubuntu:
    name: Xubuntu
    spins:
      - name: xubuntu
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/xubuntu/releases/24.04.1/release/
            path_template: xubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  lubuntu:
    name: Lubuntu
    spins:
      - name: lubuntu
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/lubuntu/releases/24.04.1/release/
            path_template: lubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  ubuntu-mate:
    name: Ubuntu MATE
    spins:
      - name: ubuntu-mate
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/ubuntu-mate/releases/24.04.1/release/
            path_template: ubuntu-mate-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  ubuntu-budgie:
    name: Ubuntu Budgie
    spins:
      - name: ubuntu-budgie
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/ubuntu-budgie/releases/24.04.1/release/
            path_template: ubuntu-budgie-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  ubuntu-studio:
    name: Ubuntu Studio
    spins:
      - name: ubuntu-studio
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/ubuntustudio/releases/24.04.1/release/
            path_template: ubuntustudio-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
  edubuntu:
    name: Edubuntu
    spins:
      - name: edubuntu
        release: 24.04.1
        version: 24.04.1
        release_title: 24.04.1
        image_type: desktop
        files:
          iso:
            url: https://cdimage.ubuntu.com/edubuntu/releases/24.04.1/release/
            path_template: edubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
