default_settings:
  datatype: image-downloads
  format: products:1.0
spin_groups:
  edubuntu:
    content_id: org.edubuntu:edubuntu
    name: Edubuntu
    spins:
      - architectures:
          - amd64
        files:
          iso:
            path_template: edubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
            url: https://cdimage.ubuntu.com/edubuntu/releases/24.04.2/release/
        image_type: desktop
        name: edubuntu
        release: noble
        release_codename: Noble Numbat
        release_title: 24.04.2
        version: 24.04.2
  kubuntu:
    content_id: org.kubuntu:kubuntu
    name: Kubuntu
    spins:
      - architectures:
          - amd64
        files:
          iso:
            path_template: kubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
            url: https://cdimage.ubuntu.com/kubuntu/releases/24.04.2/release/
        image_type: desktop
        name: kubuntu
        release: noble
        release_codename: Noble Numbat
        release_title: 24.04.2
        version: 24.04.2
  lubuntu:
    content_id: me.lubuntu:lubuntu
    name: Lubuntu
    spins:
      - architectures:
          - amd64
        files:
          iso:
            path_template: lubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
            url: https://cdimage.ubuntu.com/lubuntu/releases/24.04.2/release/
        image_type: desktop
        name: lubuntu
        release: noble
        release_codename: Noble Numbat
        release_title: 24.04.2
        version: 24.04.2
  ubuntu-budgie:
    content_id: org.ubuntubudgie:ubuntu-budgie
    name: Ubuntu Budgie
    spins:
      - architectures:
          - amd64
        files:
          iso:
            path_template: ubuntu-budgie-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
            url: https://cdimage.ubuntu.com/ubuntu-budgie/releases/24.04.2/release/
        image_type: desktop
        name: ubuntu-budgie
        release: noble
        release_codename: Noble Numbat
        release_title: 24.04.2
        version: 24.04.2
  ubuntu-mate:
    content_id: org.ubuntu-mate:ubuntu-mate
    name: Ubuntu MATE
    spins:
      - architectures:
          - amd64
        files:
          iso:
            path_template: ubuntu-mate-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
            url: https://cdimage.ubuntu.com/ubuntu-mate/releases/24.04.2/release/
        image_type: desktop
        name: ubuntu-mate
        release: noble
        release_codename: Noble Numbat
        release_title: 24.04.2
        version: 24.04.2
  xubuntu:
    content_id: org.xubuntu:xubuntu
    name: Xubuntu
    spins:
      - architectures:
          - amd64
        files:
          iso:
            path_template: xubuntu-{{ version }}-desktop-amd64.iso
            sha256: ''
            size: 0
            url: https://cdimage.ubuntu.com/xubuntu/releases/24.04.2/release/
        image_type: desktop
        name: xubuntu
        release: noble
        release_codename: Noble Numbat
        release_title: 24.04.2
        version: 24.04.2
version: 24.04.2
