spin_groups:
  edubuntu:
    name: Edubuntu
    spins:
    - files:
        iso:
          path_template: edubuntu-{{ version }}-desktop-amd64.iso
          sha256: 718afe9a7b41a8eaab78ddf7ea79e614855f6fdfb2fb1d7996065eb240a9bab5
          size: 6756536320
          url: https://cdimage.ubuntu.com/edubuntu/releases/24.10/release/
      image_type: desktop
      name: edubuntu
      release: oracular
      release_codename: Oracular Oriole
      release_title: '24.10'
      version: '24.10'
  kubuntu:
    name: Kubuntu
    spins:
    - files:
        iso:
          path_template: kubuntu-{{ version }}-desktop-amd64.iso
          sha256: 3b3c6f4b14c6609bfc296f671eccf11fed4f17702e0e675e810fa79db8fc097c
          size: 4678961152
          url: https://cdimage.ubuntu.com/kubuntu/releases/24.10/release/
      image_type: desktop
      name: kubuntu
      release: oracular
      release_codename: Oracular Oriole
      release_title: '24.10'
      version: '24.10'
  lubuntu:
    name: Lubuntu
    spins:
    - files:
        iso:
          path_template: lubuntu-{{ version }}-desktop-amd64.iso
          sha256: 5c9c3f03ea12566ecec008aef97afa997854674a1a0421d400cf48d819fd953c
          size: 3513397248
          url: https://cdimage.ubuntu.com/lubuntu/releases/24.10/release/
      image_type: desktop
      name: lubuntu
      release: oracular
      release_codename: Oracular Oriole
      release_title: '24.10'
      version: '24.10'
  ubuntu-budgie:
    name: Ubuntu Budgie
    spins:
    - files:
        iso:
          path_template: ubuntu-budgie-{{ version }}-desktop-amd64.iso
          sha256: 42c11dc83e6b949565c62325f257255d0b04c208b4f9a089a612605d98e2d414
          size: 3463921664
          url: https://cdimage.ubuntu.com/ubuntu-budgie/releases/24.10/release/
      image_type: desktop
      name: ubuntu-budgie
      release: oracular
      release_codename: Oracular Oriole
      release_title: '24.10'
      version: '24.10'
  ubuntu-mate:
    name: Ubuntu MATE
    spins:
    - files:
        iso:
          path_template: ubuntu-mate-{{ version }}-desktop-amd64.iso
          sha256: 6139a5f9bd00bac15a50e013b1f80f39098c5c4290b1f052cf88bc27871b9ae7
          size: 3521746944
          url: https://cdimage.ubuntu.com/ubuntu-mate/releases/24.10/release/
      image_type: desktop
      name: ubuntu-mate
      release: oracular
      release_codename: Oracular Oriole
      release_title: '24.10'
      version: '24.10'
  xubuntu:
    name: Xubuntu
    spins:
    - files:
        iso:
          path_template: xubuntu-{{ version }}-desktop-amd64.iso
          sha256: f0156a1efb87e4fe1aba135f9e91e6261ffc20c1933a46d06926a1c4117195b1
          size: 4270448640
          url: https://cdimage.ubuntu.com/xubuntu/releases/24.10/release/
      image_type: desktop
      name: xubuntu
      release: oracular
      release_codename: Oracular Oriole
      release_title: '24.10'
      version: '24.10'
version: '24.10'
