version: '26.04'
datatype: image-downloads
format: products:1.0
content_id: com.ubuntu.releases:ubuntu
spin_groups:
  kubuntu:
    name: Kubuntu
    content_id: org.kubuntu:kubuntu
    spins:
      - name: kubuntu
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/kubuntu-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/kubuntu/releases/26.04/release/
            sha256: '95ce9cf68f13015b9a88bd1ef86fcf7eda77c99979fda48c69e28aa0a84f88ac'
            size: 5068847104
  xubuntu:
    name: Xubuntu
    content_id: org.xubuntu:xubuntu
    spins:
      - name: xubuntu
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/xubuntu-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/xubuntu/releases/26.04/release/
            sha256: 'ae030dbd99426a4c7b2d1c96731e0f435ec9d18f6a28c9e76f077dd5f46364bc'
            size: 5183416320
  lubuntu:
    name: Lubuntu
    content_id: me.lubuntu:lubuntu
    spins:
      - name: lubuntu
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/lubuntu-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/lubuntu/releases/26.04/release/
            sha256: 'a9eef9e75c139caa428d11799f681e2d29e6ba7e22aa045d9a64599d45cd12ff'
            size: 3918290944
  ubuntu-budgie:
    name: Ubuntu Budgie
    content_id: org.ubuntubudgie:ubuntu-budgie
    spins:
      - name: ubuntu-budgie
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/ubuntu-budgie-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/ubuntu-budgie/releases/26.04/release/
            sha256: 'cbdebfa6517d6f64ecc07f6b91a672cf623e1f378b1b92c6e2d27bd7c8b6ca42'
            size: 4121487360
  edubuntu:
    name: Edubuntu
    content_id: org.edubuntu:edubuntu
    spins:
      - name: edubuntu
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/edubuntu-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/edubuntu/releases/26.04/release/
            sha256: 'e2255cca689450e368d504fbbc28a2b8086f3e871d5364ca14409391e6985ac3'
            size: 7939172352
  ubuntu-studio:
    name: Ubuntu Studio
    content_id: org.ubuntustudio:ubuntu-studio
    spins:
      - name: ubuntu-studio
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/ubuntustudio-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/ubuntustudio/releases/26.04/release/
            sha256: '900e75b0c40875d4e7c223788a94fd6cb908058780a4484c64cea5807ce3d5e0'
            size: 7141033984
  ubuntu-cinnamon:
    name: Ubuntu Cinnamon
    content_id: org.ubuntucinnamon:ubuntu-cinnamon
    spins:
      - name: ubuntu-cinnamon
        release: resolute
        version: '26.04'
        release_title: '26.04'
        release_codename: Resolute Raccoon
        image_type: desktop
        architectures:
          - amd64
        files:
          iso:
            path_template: '{{ release }}/release/ubuntucinnamon-{{ version }}-desktop-amd64.iso'
            url: https://cdimage.ubuntu.com/ubuntucinnamon/releases/26.04/release/
            sha256: '42276d3917da9b3ec8b97f924847d85b3faf07c5d12f182596455bb571431f6f'
            size: 5659195392
