default_settings:
  datatype: image-downloads
  format: products:1.0
versions:
  noble:
    version: 24.04.2
    release: noble
    release_codename: Noble Numbat
    release_title: 24.04.2
  noble_current:
    version: 25.04
    release: noble
    release_codename: Plucky Puffin
    release_title: '25.04'
file_templates:
  desktop_iso: &id002
    path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{
      arch }}.iso'
arch_amd64:
  architectures: &id001
  - amd64
base_spin:
  architectures: *id001
  image_type: desktop
  files:
    iso: *id002
spin_groups:
  ubuntu-unity:
    content_id: org.ubuntuunity:ubuntu-unity
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: ubuntu-unity
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.3G
          sha256: 52d9944c1616ebe4b81c83a126037623452223c8240d014784178149c4c27dbc
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: ubuntu-unity
  ubuntu-studio:
    content_id: org.ubuntustudio:ubuntu-studio
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: ubuntustudio
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.5G
          sha256: a5b0c3d7e9f8
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: ubuntustudio
  ubuntu-mate:
    content_id: org.ubuntu-mate:ubuntu-mate
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: ubuntu-mate
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 4.0G
          sha256: ec1399cf90678c29ee1f80055826b21a3d90f59d50d154e5ea70b1931ce909c9
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: ubuntu-mate
  edubuntu:
    content_id: org.edubuntu:edubuntu
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: edubuntu
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 5.9G
          sha256: 068359bc3bf803be0d1aea61f29384e7446451b3410f1e3dd1317ec1ff55c59f
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: edubuntu
  ubuntu:
    content_id: com.ubuntu.releases:ubuntu
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.8G
          sha256: abc123
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: ubuntu
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: def456
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: ubuntu
  xubuntu:
    content_id: org.xubuntu:xubuntu
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: xubuntu
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 4.0G
          sha256: ba76abf526b4c7ab22e8125cca69547f76559f703bd357c54bdf5d74be0bfd2b
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: xubuntu
  ubuntu-kylin:
    content_id: com.ubuntukylin:ubuntukylin
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: kylin
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.5G
          sha256: a5b0c3d7e9f8
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: kylin
  ubuntu-budgie:
    content_id: org.ubuntubudgie:ubuntu-budgie
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: ubuntu-budgie
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 4.0G
          sha256: 0b9fd288f7ad2d3936187c7f9ebf74aa755068fa5c5dc33520f40b9ba88403a1
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: ubuntu-budgie
  lubuntu:
    content_id: me.lubuntu:lubuntu
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: lubuntu
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.1G
          sha256: d29e07f791eec68f76521bd8fecd2fb15507c9aab9f8197979cbc70e117dacb1
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: lubuntu
  kubuntu:
    content_id: org.kubuntu:kubuntu
    spins:
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 3.6G
          sha256: b6c7d8e9f0a
      version: 25.04
      release: noble
      release_codename: Plucky Puffin
      release_title: '25.04'
      name: kubuntu
    - architectures: *id001
      image_type: desktop
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          size: 4.2G
          sha256: e84c3cb8a9e91504fabbc4763adaacfee0ebd27ef988529dadafb9c53276fb4b
      version: '25.04'
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      name: kubuntu
