default_settings: &default_settings
  datatype: image-downloads
  format: products:1.0

# Define common versions
versions:
  noble: &noble_lts
    version: 24.04.2
    release: noble
    release_codename: Noble Numbat
    release_title: '24.04.2'
  
  noble_current: &noble_current
    version: 25.04
    release: noble
    release_codename: Plucky Puffin
    release_title: '25.04'

# Define common file templates
file_templates:
  desktop_iso: &desktop_iso_template
    path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{ arch }}.iso'

# Define common architectures
arch_amd64: &arch_amd64
  architectures:
    - amd64

# Base spin template
base_spin: &base_spin
  image_type: desktop
  <<: *arch_amd64
  files:
    iso: *desktop_iso_template

spin_groups:
  ubuntu-unity:
    content_id: org.ubuntuunity:ubuntu-unity
    spins:
      - name: ubuntu-unity
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: ubuntu-unity
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  ubuntu-studio:
    content_id: org.ubuntustudio:ubuntu-studio
    spins:
      - name: ubuntustudio
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: ubuntustudio
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  ubuntu-mate:
    content_id: org.ubuntu-mate:ubuntu-mate
    spins:
      - name: ubuntu-mate
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: ubuntu-mate
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  edubuntu:
    content_id: org.edubuntu:edubuntu
    spins:
      - name: edubuntu
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: edubuntu
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  ubuntu:
    content_id: com.ubuntu.releases:ubuntu
    spins:
      - name: ubuntu
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.8G'
            sha256: 'abc123'
      - name: ubuntu
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'def456'

  xubuntu:
    content_id: org.xubuntu:xubuntu
    spins:
      - name: xubuntu
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: xubuntu
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  ubuntu-kylin:
    content_id: com.ubuntukylin:ubuntukylin
    spins:
      - name: kylin
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: kylin
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  ubuntu-budgie:
    content_id: org.ubuntubudgie:ubuntu-budgie
    spins:
      - name: ubuntu-budgie
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: ubuntu-budgie
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  lubuntu:
    content_id: me.lubuntu:lubuntu
    spins:
      - name: lubuntu
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: lubuntu
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'

  kubuntu:
    content_id: org.kubuntu:kubuntu
    spins:
      - name: kubuntu
        <<: *base_spin
        <<: *noble_current
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.6G'
            sha256: 'b6c7d8e9f0a'
      - name: kubuntu
        <<: *base_spin
        <<: *noble_lts
        files:
          iso:
            <<: *desktop_iso_template
            size: '3.5G'
            sha256: 'a5b0c3d7e9f8'
