default_settings:
  datatype: image-downloads
  format: products:1.0
spin_groups:
  ubuntu-unity:
    content_id: org.ubuntuunity:ubuntu-unity
    spins:
    - name: ubuntu-unity
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: '24.04'
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{
            arch }}.iso'
          sha256: d7fe3d6a0419667d2f8eff12796996328daa2d4f90cd9f87aa9371b362f987bf
          size: 6343219200
  ubuntu-studio:
    content_id: org.ubuntustudio:ubuntu-studio
    spins:
    - name: ubuntustudio
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: '24.04'
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{
            arch }}.iso'
          sha256: d7fe3d6a0419667d2f8eff12796996328daa2d4f90cd9f87aa9371b362f987bf
          size: 6343219200
  ubuntu-mate:
    content_id: org.ubuntu-mate:ubuntu-mate
    spins:
    - name: ubuntu-mate
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: '24.04'
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{
            arch }}.iso'
          sha256: d7fe3d6a0419667d2f8eff12796996328daa2d4f90cd9f87aa9371b362f987bf
          size: 6343219200
  edubuntu:
    content_id: org.edubuntu:edubuntu
    spins:
    - name: ubuntu
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: '24.04'
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{
            arch }}.iso'
          sha256: d7fe3d6a0419667d2f8eff12796996328daa2d4f90cd9f87aa9371b362f987bf
          size: 6343219200
  ubuntu:
    content_id: com.ubuntu.releases:ubuntu
    spins:
    - name: ubuntu
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: '24.04'
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type }}-{{
            arch }}.iso'
          sha256: d7fe3d6a0419667d2f8eff12796996328daa2d4f90cd9f87aa9371b362f987bf
          size: 6343219200
  xubuntu:
    content_id: org.xubuntu:xubuntu
    spins:
    - name: xubuntu
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          sha256: ba76abf526b4c7ab22e8125cca69547f76559f703bd357c54bdf5d74be0bfd2b
          size: 4242739200
  ubuntu-kylin:
    content_id: com.ubuntukylin:ubuntukylin
    spins:
    - name: kylin
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: '24.04'
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          sha256: ba76abf526b4c7ab22e8125cca69547f76559f703bd357c54bdf5d74be0bfd2b
          size: 4242739200
  ubuntu-budgie:
    content_id: org.ubuntubudgie:ubuntu-budgie
    spins:
    - name: ubuntu-budgie
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          sha256: 0b9fd288f7ad2d3936187c7f9ebf74aa755068fa5c5dc33520f40b9ba88403a1
          size: 4248414208
  lubuntu:
    content_id: me.lubuntu:lubuntu
    spins:
    - name: lubuntu
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          sha256: d29e07f791eec68f76521bd8fecd2fb15507c9aab9f8197979cbc70e117dacb1
          size: 3352426496
  kbuntu:
    content_id: org.kubuntu:kubuntu
    spins:
    - name: kubuntu
      image_type: desktop
      version: 24.04.2
      release: noble
      release_codename: Noble Numbat
      release_title: 24.04.2
      architectures:
      - amd64
      files:
        iso:
          path_template: '{{ release }}/release/{{ name }}-{{ version }}-{{ image_type
            }}-{{ arch }}.iso'
          sha256: e84c3cb8a9e91504fabbc4763adaacfee0ebd27ef988529dadafb9c53276fb4b
          size: 4527759360
